### ISSUE TITLE
Lipo

### ISSUE THREAD

**Issue by mrs404** [JoernL/LimiTTer#7]
Where can I get a suitable lipo battery in the UK. Any help appreciatedesk.

**Comment by jotomo** [comment]
Try the Gitter channel (see main repo page), there are more people listening.
I was hunting down a 110mAh Lipo some weeks ago, got one but it turned out be broken. The 110mAh ones are tricky to come by these days, I didn't find another source.
I ended up using a 550mAh from Amazon which fitted into the big version of the LimiTTer and which has been running for 6 days now and still has 46%.
